PALAVRAS = [
"ABACO","ABRIR","ACIDO","ACUME","ADUBA",
"AFAGO","AGUAS","ALADO","ALUVI","AMBAR",
"ANEXO","ANIMO","APICE","ARIDO","ARQUE",

"BALSA","BANDO","BARDO","BISPO","BRUMA",
"BURIL","CACAU","CALIX","CAMPO","CANIL",
"CARMA","CAVAL","CEDRO","CELTA","CERNE",

"CHAGA","CISMA","CLAVA","COESA","CORVO",
"CRIVO","CRUZA","CULTO","DAGMA","DADOS",

"DECOR","DEDOZ","DENSO","DESDE","DOTAL",
"DRAMA","EBANO","ECOAR","EDIPO","EFETA",

"EGIDE","ELIXI","ENODO","ENTAO","ERETA",
"FARDO","FENIX","FERAZ","FIBRA","FLORE",

"FUGAZ","GARRA","GAUCHO","GENIO","GERME",
"GRUTA","HEROI","HIFEN","HUMUS","ICONE",

"IDEAL","IMPAR","INATO","INDIO","JAULA",
"JUNCO","LAPSO","LARVA","LESTE","LIRIO",

"LIVRO","MACRO","MAGMA","MANIA","MELRO",
"MENTE","MISTO","MORFO","NOBRE","NOCHE",

"OCASO","ODIOS","ORVAL","OSSEO","PANDA",
"PENAL","PERIL","PLUMA","PRADO","QUIOS",

"RASTO","RELES","RISCO","ROTOR","SAGAZ",
"SALMO","SENIL","SERVO","SONDA","TACAO", 

"ZEBRA",

"ABACO","ABRIR","ACASO","ACHAR","ADEUS",
"AGORA","AJUDA","ALUNO","AMIGO","AMORA",

"ANDAR","ANEXO","ANTES","APOIO","AREIA",
"ARROZ","ARTES","ATLAS","AUTOR","AVIAO",

"BAIXA","BANCO","BANHO","BARCO","BEBER",
"BEIJO","BICHO","BLOCO","BOLSA","BRAVO",

"CABER","CABRA","CAIXA","CALMA","CAMPO",
"CANAL","CANTO","CARNE","CARRO","CARTA",

"CASAL","CHAVE","CHUVA","CINCO","CIRCO",
"CLARO","COBRA","COISA","CORPO","CRISE",

"DADOS","DANCA","DEIXA","DENTE","DEVER",
"DIZER","DOIDO","DOLAR","DRAMA","DUPLA",

"ECOAR","EDITA","EMAIL","ENFIM","ERROS",

"FACIL","FALAR","FALHA","FAROL","FAZER",
"FEIRA","FELIZ","FERRO","FESTA","FILHO",

"FORCA","FORMA","FORTE","FRUTA","FUNDO",

"GRAMA","GRUPO","HONRA","HOTEL","HUMOR",

"IDEIA","IGUAL","JOGAR","JOVEM","JUSTO",

"LAPIS","LEITE","LETRA","LIVRO","LUGAR",

"MAIOR","MUNDO","NADAR","NAVIO","NORTE",

"OLHAR","OUVIR","PEDRA","PODER","PRAIA",


"TABUA","TACAR","TALAO","TALCO","TALHA","TAMPA","TANGO","TAPAR",
"TARDE","TARJA","TATUA","TAXAS","TECLA","TEDIO","TEMAS","TEMPO",
"TENDA","TENHO","TERCA","TERMO","TERRA","TESOU","TESTE","TEXTO",
"TIGRE","TILDE","TIMAO","TINHA","TINTA","TIRAR","TOCAR","TODOS",
"TOGAR","TOMAR","TONEL","TORNO","TORRE","TOTAL","TOUCA","TOURO",
"TRACO","TRAMA","TRATO","TRETA","TREVO","TRIGO","TRONO","TROPA",
"TROCA","TROVA","TUBAR","TUBOS","TURMA",

"UNIAO","UNIDO","UNICA","UNICO","URINA","URUBU","USADO","USINA",

"VACAS","VAGAO","VAGAR","VALER","VALIA","VALOR","VARAL","VARAO",
"VARIA","VARIO","VASTO","VAZIO","VELAR","VELHA","VELHO","VENDA",
"VENDO","VENTO","VERAO","VERDE","VERBO","VERME","VERSO","VESPA",
"VETOR","VIAJA","VIOLA","VIRAR","VIRUS","VISOR","VISTA","VITAL",
"VIVER","VIVIA","VOGAL","VOLAR","VOLUME",

"ZANGA","ZEBRA","ZELAR","ZINCO",

"ABRIR","ACORD","ADUBA","AGITA","AJUDA","ALAGA","ALAVA",
"ALINA","ALMAS","AMPLA","ANJOS","ANUAL","APAGA","APICE",
"APOIA","ARADO","ARCAR","ARMAS","ARREM","ATACA",

"BAFAR","BAHIA","BAIXE","BALDE","BALSA","BANDE","BANHA",
"BARBA","BARCO","BATEM","BATIA","BEATA","BEIJO","BEIRA",
"BICAR","BISPO","BOATE","BOINA","BOLAO","BOLHA","BOLSO",
"BORRA","BRAVA","BRAVO","BREVE","BRIGA","BROTA",

"CAIXA","CALAR","CALDO","CALHA","CALMO","CAMPO","CANAL",
"CANIL","CANTO","CAPAS","CARNE","CARPA","CARRO","CARTA",
"CASAR","CASCO","CASTA","CAUSA","CEDER","CEGAR","CERCA",
"CHAVE","CHORO","CHUVA","CINTO","CIRCO","CLARO","CLUBE",
"COBRA","COBRE","COISA","COLAR","COLME","COMER","COMUM",
"CONTA","CORAL","CORPO","CORRE","COSTA","CRAVE","CRIAR",

"DANAR","DANCA","DARAO","DADOS","DEBIL","DEDOS","DEIXA",
"DEMON","DENTE","DESCE","DESTA","DEVER","DIETA","DILUI",
"DINHO","DIRET","DISCO","DOADO","DOBRA","DOIDO","DOLAR",
"DORAR","DRAMA","DUPLA",

"ECOAR","EDITA","ELEVA","EMANA","EMBAS","EMPEN","ENCHE",
"ENTRA","ENVIO","ERETA","ERRAR","ESSAS","ESTES",

"FALAR","FALHA","FARPA","FATAL","FAVOR","FAUNA","FAUNA",
"FENDA","FERIR","FERVO","FIBRA","FICOU","FILHA","FILME",
"FIRME","FLAUT","FLETA","FLOCO","FOICE","FOLGA","FORTE",
"FRACO","FRUTA","FUGIR",

"GALHO","GANHA","GARFO","GARRA","GASTO","GATIL","GEADA",
"GERAL","GERAR","GIRAR","GOLFO","GOLPE","GORDA","GOSTO",
"GRAMA","GRATO","GRUPO",

"HASTE","HAVIA","HEROI","HINOS","HOMEM","HONRA","HORDA",
"HUMOR",

"IMUNE","INATO","INCHA","INDIO","INVER","IRADO","IRMAS",

"JANTA","JOGOS","JUNTA","JURAR",

"LAPSO","LARVA","LARGO","LASER","LEBRE","LEGAL","LENDA",
"LESTE","LEVAR","LIMAR","LIMPA","LIMPO","LINHA","LITRO",
"LIVRO","LOCAL","LOMBO","LOUCO",

"MACHO","MADRE","MAFIA","MAGRO","MANGA","MANHA","MARCA",
"MASSA","MATAR","MEDAL","MEDIR","MELRO","MENOR","MENTE",
"MERDA","MESMO","METRO","MILHA","MINAR","MINHA","MISTO",
"MOEDA","MOLDE","MONTE","MORAL","MORAR","MOTOR","MUDAR",

"NABOS","NADAR","NARIZ","NEGRO","NINHO","NIVEL","NOBRE",
"NOITE","NORTE","NUNCA",

"OCASO","OCULO","ODIAR","OLEOS","ONDAS","OPACO","ORDEM",

"PALCO","PALHA","PANDA","PAPEL","PARAR","PARDO","PARTE",
"PASSA","PATIO","PAUSA","PEDRA","PEGAR","PEITO","PENSA",
"PERDA","PERTO","PESCA","PIANO","PILHA","PINTO","PISAR",
"PLANO","PODER","POEMA","POMBA","PONTE","PONTO","PORCO",
"PORTA","POSSE","PRATA","PRECO","PRETO","PROVA",

"RAIOS","RAMOS","RASGO","REBAN","REINO","REMAR","RENDA",
"RESTO","RETAS","RISCO","ROCHA","RODAR","ROLHA","ROUPA",

"SACIA","SAFRA","SALAO","SALTO","SAUDE","SECAO","SENHA",
"SERIA","SERIO","SERRA","SOBRA","SOCIO","SOLTO","SONAR",
"SONHO","SORRI","SORTE","SUAVE","SUBIR","SURDO",


"ABRIGO","ACENO","ACESA","ACIMA","ACUAR","ADAGA","ADEUS",
"AFAGO","AFINS","AGUDO","AJUDE","ALCEM","ALDEA","ALEM",
"ALICE","ALUNO","AMPLA","ANOTA","APAGA","APOIA","APURA",
"ARADO","ARAME","AREAL","AREIA","ARMAR","AROMA","ARQUE",
"ARRAS","ASILO","ATIRA","ATIVO","ATRIO","AUREO",

"BAFIO","BAILE","BAIXA","BALAO","BALSA","BANDO","BARAO",
"BARBA","BARRA","BATAL","BATIA","BEBIA","BEIJA","BEIRA",
"BEMTE","BICHO","BIRRA","BLUSA","BOCAI","BOLAO","BOLHA",
"BORDA","BORRA","BRADO","BRAVA","BRAVO","BREJO","BRISA",

"CABRA","CACAU","CAFEI","CALCA","CALDO","CALHA","CALMA",
"CALVO","CAMAS","CANCA","CANIL","CANOA","CAPA","CAPTA",
"CARAO","CARPA","CARVA","CASAR","CAUSA","CEASA","CEDRO",
"CEGAR","CESTA","CHAGA","CHAMA","CHATO","CHEIA","CHUCO",
"CIFRA","CINZA","CIRCO","CLIMA","CLUBE","COBRE","COCAI",
"COISA","COLAR","COLHE","COMUM","CONDE","COPOS","CORAL",
"CORDA","CORVO","COSTA","COVAS","CRAVO","CREME","CRIAN",
"CRUZA",

"DAMAS","DADOS","DANCA","DARDO","DEBIL","DECOR","DEDOS",
"DEITA","DEIXA","DEMAN","DENTE","DEPOR","DESCE","DESDE",
"DEVER","DEVIA","DIETA","DIOGO","DISCO","DIZER","DOBRA",
"DOADO","DORES","DORAR","DRAGA","DRAMA",

"EDITOR","EIXOS","ELITE","EMANA","EMITE","ENFIA","ENROL",
"ENTRA","ENVIO","ERROS","ESSAS","ESTIO",

"FACES","FACIL","FALHA","FALTA","FARPA","FAROL","FAUNA",
"FAVOR","FEIRA","FERIA","FERRO","FESTA","FIBRA","FICAR",
"FICHA","FIEL","FILHA","FILME","FINAL","FIRMA","FIRME",
"FLETA","FLOCO","FLORA","FOCAR","FOLHA","FOLIA","FORCA",
"FORMA","FORNO","FORTE","FRACO","FRUTA","FUGAS","FUNDO",

"GABAR","GAITA","GALHO","GAMBA","GANHO","GARFO","GAROA",
"GATOS","GEADA","GELAR","GEMAS","GENIO","GERAL","GIRAR",
"GOLPE","GORRO","GOSTO","GRADE","GRAMA","GRANA","GRATO",

"HABIT","HASTE","HAVIA","HERDE","HEROI","HINOS","HONRA",
"HORAS","HOTEL","HUMOR",

"IDEAL","IDEIA","IDOSO","IGUAL","IMPAR","INDIO","INOVA",
"IRADO","IRMAS","ISOLA",

"JOGAR","JOGOS","JOVEM","JUNCO","JUNTA","JUSTA",

"LABIO","LAGOA","LAMPI","LANCA","LAPIS","LARAN","LARVA",
"LARGO","LASCA","LEGAL","LEITE","LENDA","LENHO","LETRA",
"LEVAR","LIGAR","LIMAO","LIMPO","LINHA","LISTA","LIVRE",
"LOCAL","LOMBO","LOUCO","LUCRO","LUGAR",

"MACIO","MADURO","MAGIA","MAGRO","MAIOR","MALHA","MAMAE",
"MANDA","MANHA","MARCA","MARCO","MARTE","MASSA","MATAR",
"MEDIR","MEDIO","MEIAS","MELAO","MENOS","MENTE","MESMO",
"METAL","METRO","MILHO","MINHA","MISTO","MOEDA","MOLAR",
"MOLHO","MONTE","MORAL","MORAR","MORTE","MOTOR","MUDAR",
"MUNDO",

"NABOS","NADAR","NARIZ","NAVAL","NAVIO","NEGAR","NEGRO",
"NEVAR","NINHO","NIVEL","NOBRE","NOITE","NORTE","NOTAR",
"NUNCA",

"OBESO","OBTER","OCUPA","ODIAR","OLHAR","OLHOS","ONTEM",
"OPACO","OPERA","ORDEM","OUVIR",

"PADRA","PADRE","PAGAR","PAIRA","PALCO","PALHA","PANEL",
"PAPEL","PARAR","PARTE","PASSO","PASTA","PATIO","PAUSA",
"PEDAL","PEDIR","PEDRA","PEGAR","PEITO","PENAL","PENSA",
"PERDA","PERNA","PERTO","PESCA","PIANO","PILHA","PINTO",
"PIRAO","PISAR","PLANO","PLUMA","PODER","POEMA","POMBO",
"PONTE","PONTO","PORCO","PORTA","POSSE","PRATA","PRETO",
"PROVA","PUDER","PULAR",

"QUASE","QUEDA","QUILO","QUINA","QUOTA",

"RAIVA","RAMPA","RASGO","RASTO","REGRA","REINO","RENDA",
"RESTO","RETRO","RISCO","RITMO","ROCHA","RODAR","ROSTO",
"ROUPA","RUGIR",

"SABAO","SABER","SACAR","SAFRA","SAIDA","SALTO","SANTO",
"SAUDE","SECAO","SECAR","SEGUE","SENHA","SERIA","SERIO",
"SERRA","SETOR","SINAL","SINTO","SOBRA","SOLAR","SONHO",
"SORTE","SUAVE","SUBIR","SURDO","SUSTO",

"QUASE","QUEBR","QUEDA","QUILO","QUINA","QUOTA",

"RAIVA","RAMPA","RAMOS","RASGO","RASTE","RATAR","RAZAO",
"RECEM","REDOR","REGRA","REINO","RELAR","RENDA","RESTO",
"RETAS","RISCO","RITMO","ROCHA","RODAS","ROSTO","ROUPA",
"RUIDO","RUGIR",

"SABAO","SABER","SABIA","SACAR","SACIO","SAFRA","SAIDA",
"SAUDE","SALAO","SALTO","SALVE","SANTO","SECAR","SEDAI",
"SEGUE","SENHA","SENIL","SERIE","SERIO","SERRA","SETOR",
"SEXTA","SINAL","SINTO","SITIO","SOBRA","SOCIO","SOLAR",
"SOMAR","SONAR","SONHO","SORGO","SORTE","SUAVE","SUBIR",
"SUINO","SURDO","SURTO","SUSTO",

"TABUA","TACAR","TALCO","TALHA","TANGO","TAPAR","TARDE",
"TARJA","TAXAS","TECLA","TEMAS","TEMPO","TENDA","TENHO",
"TERMO","TERRA","TESTE","TEXTO","TIGRE","TILDE","TIMAO",
"TINTA","TIRAR","TOCAR","TODOS","TOMAR","TONEL","TORRE",
"TOTAL","TOURO","TRACO","TRAMA","TRATO","TRETA","TREVO",
"TRIGO","TRONO","TROCA","TROVA","TUBOS","TURMA",

"UNIAO","UNIDO","UNICO","URINA","URUBU","USADO","USINA",

"VACAS","VAGAO","VAGAR","VALER","VALOR","VARAL","VARIA",
"VARIO","VASTO","VAZIO","VELAR","VELHA","VELHO","VENDA",
"VENDO","VENTO","VERAO","VERDE","VERBO","VERME","VESPA",
"VETOR","VIAJA","VIOLA","VIRAR","VIRUS","VISTA","VITAL",
"VIVER","VIVIA","VIZIN",

"ZANGA","ZEBRA","ZELAR","ZINCO",

"ABRACO","ACIDO","ACORD","ADOTE","AEREO","AGITO","ALICE",
"AMIGO","ANIMO","ANUAL","APOCA","ARADO","ARIDO","ARMAZ",
"ATIVO",

"BAGRE","BALDE","BANDE","BARBA","BARIL","BATAL","BEBEU",
"BIELA","BIGODE","BISPO","BOINA","BORBO","BRIGA",

"CAIXA","CALHA","CALMO","CAMEO","CAMPO","CANCA","CANOE",
"CARPA","CARVA","CAVAR","CEBOL","CERVO","CHICO","CHINA",
"CHOCO","CINZA","CISMA","CLERO","CLUBE","COBRA","COCHO",
"COFRE","COIFA","COLME","CORVO","COVIL","CRONO",

"DENTE","DILUI","DISCO","DOBRO","DORES","DRONE","DUPLO",

"EMBAR","EMPEN","ENCHE","ENERO","ENTRE","ERETO","ESPIR",
"ESSAS",

"FARPA","FATIA","FAVOS","FENDA","FERIR","FERVO","FIBRA",
"FICHA","FIRME","FLETA","FLOCO","FOICE","FORNO","FOSCO",

"GALAO","GAMAS","GANHA","GAROA","GELAO","GENTE","GELOU",
"GRAUS","GRITO",

"HABIL","HAVIA","HELIC","HONRA","HUMOS",

"IMAGEM","IMERS","IMITA","INATO","INDIA","INVER","ISOLA",

"JANTA","JURAR","JULGA",

"LAGAR","LAUDO","LATIM","LEAOZ","LENTO","LIMPA","LITRO",
"LOGAR","LUCRO","LUTAS",

"MAMAE","MANIA","MAPAS","MARTA","MELRO","MENINA","MENSO",
"MESAS","MILHA","MINAS","MOLDE","MONJA","MORNO","MOTEL",

"NABOS","NARCO","NASAL","NATUR","NECAS","NINAR","NOBRE",

"OCASO","OCULO","OLEOS","ONDAS","OPACO","ORVAL",

"PALCO","PALHA","PANDA","PANOS","PAPAI","PARDO","PARED",
"PARES","PARIS","PATIO","PAVAO","PEIXE","PENAL","PENSA",
"PERNA","PESOS","PILAO","PIRATA","PNEUS","POLVO","PORAO",
"PRAGA","PRATA","PRESS","PUDIM",

"RAIOS","RANHO","RASTE","REBAN","REFIL","RELOG","REMAR",
"ROBAR","RODAO","ROLHA","ROMBO",

"SACIA","SALVE","SENOR","SOBRE","SOGRA","SOPRO","SORRI",

"TAMPA","TARJA","TATUA","TENDO","TENTO","TERCA","TERRA",
"TEXAS","TILHA","TOUCA","TRAVA","TREMO",

"VALSA","VAPOR","VARAO","VASSO","VELAR","VENAL","VERME",
"VICIO","VIDEO","VIGOR","VINHO","VOLAR","VOLUME",
"ABACO","ABALO","ABANA","ABATE","ABETO","ABRIR","ABRUM","ABUSA",
"ACASO","ACENO","ACHAR","ACIMA","ACODE","ACUSA","ADAGA","ADEGA",
"ADIAR","ADUBO","AFETO","AFIAR","AGARR","AGORA","AGUDO","AJUDA",
"ALADO","ALARO","ALBUM","ALCAL","ALEGR","ALENO","ALUNO","AMADO",
"AMBAR","AMIGO","AMORA","AMPLO","ANCHO","ANDAR","ANELA","ANEXO",
"ANIMA","ANOTA","ANTES","ANTRO","APEAR","APELA","APITO","APOIO",
"ARAME","ARARA","ARCAR","AREIA","ARENA","AROMA","ARQUE","ARROZ",
"ARTES","ASILO","ASMAR","ASSIM","ASTRO","ATADO","ATEAR","ATLAS",
"ATOMO","ATUAL","AUDIO","AULAS","AUTOR",

"BAFAR","BAIXA","BAIXO","BALAO","BANCO","BANHO","BARCO","BARRO",
"BASTA","BATOM","BEBER","BEIJO","BEIRA","BEMOL","BENTO","BICHO",
"BILHA","BINGO","BLOCO","BOATO","BOLAO","BOLSA","BOLSO","BOMBA",
"BONDE","BORDA","BORRA","BOTAO","BRACO","BRASA","BRAVO","BREVE",
"BRIGA","BRISA","BROTO","BUCHA","BURRO",

"CABAL","CABER","CABOS","CABRA","CACAU","CACTO","CALCA","CALDO",
"CALMA","CALOR","CAMPO","CANAL","CANJA","CANTO","CAPAZ","CAPIM",
"CARNE","CARRO","CARTA","CASAL","CASAS","CASCO","CASPA","CASTA",
"CATAR","CAUSA","CEDER","CEDRO","CEGAR","CELTA","CENSO","CERCA",
"CESTA","CHAMA","CHAPA","CHAVE","CHATO","CHEFE","CHORO","CHUVA",
"CICLO","CINCO","CIRCO","CISNE","CLARO","CLIMA","CLUBE","COBRA",
"COBRE","COCAR","COISA","COLAR","COLHE","COMER","CONTA","COPIA",
"CORAL","CORDA","CORPO","CORRE","COSTA","COTAR","CRAVO","CRIAR",
"CRISE","CRUZA","CULPA","CURSO",

"DADOS","DANCA","DARDO","DEITA","DEIXA","DELTA","DENTE","DENSO",
"DESDE","DEVER","DIADE","DIETA","DIGNO","DIZER","DOBRA","DOADO",
"DOCE","DOIDO","DOLAR","DOMAR","DORME","DORNA","DRAMA","DUPLA",

"ECOAR","EDITA","EFEITO","ELEGE","ELITE","EMAIL","EMITE","ENFIM",
"ERRAR","ERVAS","ESTAR","ETAPA","EXAME","EXATO",

"FACAO","FACIL","FALAR","FALHA","FALTA","FARDO","FAROL","FAZER",
"FEIRA","FEITO","FELIZ","FERRO","FESTA","FICAR","FICHA","FILHO",
"FILME","FINAL","FIRMA","FIRME","FLORA","FLUIR","FOBIA","FOCAR",
"FOLHA","FOLIA","FORCA","FORMA","FORTE","FORNO","FOSSA","FRACO",
"FRASE","FREIO","FREVO","FRUTA","FUGIR","FUNDO",

"GABAR","GAITA","GALHO","GANHO","GARFO","GAROA","GASTO","GATOS",
"GELAR","GEMAS","GENIO","GERAL","GERAR","GIRAR","GLOBO","GOLFE",
"GOLPE","GOSTO","GRADE","GRAMA","GRANA","GRATO","GRUPO",

"HASTE","HAVER","HEROI","HOMEM","HONRA","HORAS","HOTEL","HUMOR",

"IDEAL","IDEIA","IDOSO","IGUAL","IMPAR","IMUNE","INDIO","INICIO",
"IRADO","IRMAO",

"JANTA","JOGAR","JOVEM","JUNTA","JUSTO",

"LAGOA","LANCE","LAPIS","LARVA","LARGA","LASER","LEBRE","LEGAL",
"LEITE","LENDA","LENHA","LETRA","LEVAR","LIGAR","LIMAO","LIMPA",
"LIMPO","LINHA","LISTA","LIVRO","LIVRE","LOCAL","LOUCO","LUGAR",
"LUTAR",

"MACIO","MADRE","MAGIA","MAGRO","MAIOR","MALHA","MANGA","MANHA",
"MARCA","MARCO","MASSA","MEDIR","MEDIO","MELAO","MENOS","MENTE",
"METAL","METRO","MILHO","MINHA","MISTO","MOEDA","MOLHO","MONTE",
"MORAR","MORTE","MOTOR","MUNDO","MURAL","MUSGO","MUSICA",

"NACAO","NADAR","NARIZ","NAVIO","NEGAR","NEGRO","NEVOA","NINHO",
"NIVEL","NOBRE","NORTE","NOSSA","NOTAR","NUVEM",

"OBTER","OCUPA","ODIAR","OLHAR","OLHOS","ONTEM","OPCAO","OPERA",
"ORDEM","OUVIR",

"PADRE","PAGAR","PANEL","PAPEL","PARAR","PARTE","PASSA","PASTA",
"PATOS","PAUSA","PEDAL","PEDRA","PEGAR","PEITO","PERDA","PERTO",
"PESCA","PIANO","PILAR","PILHA","PINTO","PISAR","PLANO","PLUMA",
"PODER","POEMA","POMBA","PONTE","PONTO","PORCO","PORTA","POSSE",
"PRATO","PRAIA","PRECO","PRETO","PRIMO","PROVA","PULAR",
"ABRUP","ACENO","ACOLA","ACUAR","ADAGA","ADIDO","AFINS","AGAPE",
"AGAVE","ALCEU","ALFAS","ALGUM","ALHEI","ALMOR","ALTAR",
"AMENO","AMPLA","ANUAL","ANUEM","APITO","APURO","ARADO","ARGIL",
"ARIDO","ARPEJ","ARQUI","ARVOR","ASCIA","ASTRA","ATIVA","ATUAR",

"BABEL","BACIA","BAFIO","BALDA","BALDE","BAMBO","BANAL","BANCO",
"BARAO","BARRO","BATEL","BEATA","BEDEL","BEIJO","BELGA","BENTO",
"BERCO","BILRO","BISAR","BOLHA","BORLA","BRASA","BREUO","BRUMA",

"CAIBR","CAIRO","CALDO","CALVO","CAMPO","CANAL","CANHA","CAPPA",
"CARDO","CARIE","CARVA","CASAR","CASTO","CATRE","CAUDA","CAVAR",
"CEIFA","CEITA","CENHO","CERVO","CHAMA","CHAGA","CHINA","CHUCA",
"CINZA","CIVIL","CLERO","CLIVO","COBRE","COCHA","CODOR","COESA",
"COITO","COLMO","COMAR","CONTO","COPAL","CORAL","COROA","CORVO",
"COSMO","COTIA","CRASE","CRINA","CRIVO","CROMO",

"DAMNO","DANOS","DENSI","DEPOR","DERMA","DESCE","DIABO","DICAR",
"DIGNA","DILMA","DIONE","DISSO","DIVAS","DOBLE","DOCIL","DORSO",
"DOTAL","DRAGO","DRAPE","DUPLO",

"EBANO","EFLUV","EGIDE","EIXAR","ELITE","EMULO","ENASE","ENODO",
"ENTRE","ERGUI","ERVAL","ESFER","ESTIO","ETNIA","EXATO",

"FACAO","FAGUL","FALSA","FARPA","FATOS","FAUNO","FENDA","FENIX",
"FERAL","FERAZ","FERIR","FESTA","FIADO","FIBRA","FIELA","FIRME",
"FISCO","FLEMA","FLUOR","FOICE","FOLGO","FORJA","FOSCO","FRUIR",

"GALHO","GANHA","GARIM","GAROA","GARRA","GASOS","GELAR","GEMER",
"GENRO","GERME","GESSO","GIRIA","GIZAR","GLOSA","GOMOS","GRAMA",
"GRANA","GRATO","GRIFO","GRUTA",

"HABIT","HALOZ","HARPA","HASTE","HENRI","HERDA","HIDRA","HINOS",
"HIPER","HONRA","HORDA","HUMUS",

"ICONE","IDEAL","IDOSO","IMUNE","INATO","INDUZ","INGRE","IRADO",

"JACAR","JUNCO","JURAR","JUSTO",

"LAPSO","LARVA","LASCA","LATIR","LAURO","LEIGO","LENDA","LEQUE",
"LERDO","LESMA","LETAL","LIMBO","LIMPO","LINHO","LIRIO","LITRO",
"LOGRO","LOUCA","LUCRO","LUMEN",

"MACIO","MADRE","MAGMA","MAIOR","MALTE","MAMBA","MANSA","MARCO",
"MARGEM","MELRO","MERCE","METRO","MICRO","MILHO","MINAR","MOLAR",


"MONTE","MORFO","MORRO","MOVER","MUSGO","MUTUA","NABLA","NARCO",
"NATAL","NAVAL","NEGAR","NEGRO","NEVOA","NEXOS","NIMBO","NINFA",
"NOBRE","NOCAO","NODAL","NORMA","NOTAS","NUVEM","NUTRI",

"OBESO","OBICE","OBTUR","OCASO","OCULO","ODIAR","OFITO","OGIVA",
"OLEOS","OLIVA","OMNIA","OPALA","OPERO","ORBIT","ORFAN","ORGIA",
"ORVAL","OSMIO","OSSEO","OSTRA",

"PACTO","PAGAO","PALCO","PALHA","PANOS","PAPEL","PARCO","PARDO",
"PARES","PARVO","PASSE","PASTO","PAVIO","PEADO","PEDRA","PEGAI",
"PELAS","PENAR","PENSA","PERIL","PERLA","PESAR","PIADO","PILAR",
"PINHA","PIPAS","PIRAO","PISCA","PITON","PLAGA","PLANO","PLENO",
"PLUMA","POEMA","POETA","POLPA","POMAR","PONTO","PORCA","PORTE",
"POSAR","PRADO","PRAGA","PRIMO","PROLE","PRUMO",

"QUARK","QUINA","QUOTA","QUIBE","QUICO","QUOTA",

"RAIAR","RAMAL","RAPAZ","RASTE","RASTO","RAZIA","RECIO",
"REDIL","REGIO","RELES","REMAN","REMOS","RENAL","RENDA",
"REVER","REVES","RIGOR","RIMAS","RINHA","RIRAM","RISCA",
"ROCHA","RODIO","ROGAR","ROLAR","ROMBO","RONCO","ROSCA",
"ROTAS","ROTOR","RUBOR","RUFAR",

"SABIA","SABIO","SAGAZ","SAETA","SALMO","SALVE","SAPAO",
"SARAU","SEARA","SEBOS","SEIVA","SELIM","SENIL","SENSO",
"SERVO","SIGLA","SINAL","SISAL","SOBER","SOBRA","SOCAR",
"SODIO","SOLAR","SOLDO","SONDA","SONSO","SORVO","SUAVE",
"SUECO","SUINO","SULCO","SUMIR","SUPOR",

"TABOR","TACAO","TALAR","TAMPA","TANGO","TARSO","TATIL",
"TEIAS","TELHA","TEMOR","TENAZ","TENIS","TERNO","TERRA",
"TEXTO","TIGRA","TILIA","TIMBO","TIRSO","TITAN","TOADA",
"TOCAR","TODAS","TOLDO","TOMBO","TONAL","TORAX","TORPE",
"TRAMA","TRAVE","TREPA","TREVO","TRIAR","TRIBO","TRONO",
"TROPA","TROTE",

"ULTRA","UNHAS","URANO","URDIR","URGEI","URUBU",

"VACUO","VADIO","VALIA","VALOR","VAPOR","VARAL","VARIA",
"VASTO","VELAR","VENAL","VERAZ","VERBA","VERDE","VERGA",
"VERSO","VESGO","VETOR","VIGIA","VINCO","VINHA","VIRIL",
"VIRUS","VISCO","VITAL","VITRO","VULGO",

"ZELAR","ZOMBA","ZUNIR",

"ABALO","ACIDA","ADORA","AFETA","AGORA","ALADO","ALMAS",
"AMADO","AMIDO","ANIMO","APAGA","AROMA","ATIRA",

"BANDO","BARCA","BATIA","BEBIA","BICAR","BOATO","BONDE",
"BRIGA","BRISA",

"CAIXO","CALAR","CANJA","CAPAZ","CARTA","CEDER","CEGAR",
"CHORO","CLIMA","COCAR","COISA","COMUM","CONTA","CORTE",
"CRUEL",

"DEDAL","DEIXO","DEVER","DICHA","DIZIA","DOADO","DOIDO",
"DRAMA",

"EDITO","EMITE","ERROS","ESTAR",

"FALAR","FAROL","FAZER","FECHO","FUGAZ",

"ABRIR","ACENO","ACUDE","ADERE","AFETO","AGUDO","AJUDE",
"ALBUM","ALDEA","ALGOR","ALUDE","AMPLA","ANEXA","ANZOL",
"APICE","APURA","ARAME","ARGOS","ARIDO","ARMAR","ARREM",
"ASSAR","ATADO","ATIVA","ATUOU",

"BACIA","BAIXO","BALAO","BANHO","BARDO","BARRA","BATOM",
"BEBEU","BEIJA","BELAS","BOLAO","BORDA","BOSSA","BOTAO",
"BRACO","BRAVO","BREJO",

"CABAL","CABOS","CACAU","CADAR","CAIRO","CALMA","CALOR",
"CAMPO","CANOE","CAPIM","CARPA","CARVA","CASCA","CAUSA",
"CEDRO","CELTA","CERNE","CHAVE","CHICO","CISMA","CLAVA",
"COBRA","COFRE","COIFA","COLAR","COMER","CONDE","CORAL",
"CORPO","COTAS","CRAVO","CREME","CRINA",

"DANCA","DARDO","DEBIL","DECOR","DEDOS","DEITA","DELTA",
"DENSO","DESSE","DEVEM","DIABO","DIADE","DIETA","DIGNO",
"DILUI","DINHO","DISCO","DIVIR","DOBRA","DOCES","DOLAR",
"DRAGA","DRONE",

"EBRIO","ECOOU","EDITA","EFETO","EGITO","ELISA","EMANA",
"EMBOL","EMULO","ENFIM","ENGAS","ENTAO","ERETO","ERVIL",
"ESPIA","ESSAS",

"FACIL","FADAR","FALIR","FALTA","FARDA","FARDO","FARPA",
"FATAL","FAVOS","FEIRA","FELPA","FERRO","FICHA","FIGOS",
"FILME","FINCA","FIRMA","FISCO","FLETA","FLORA","FLUIR",
"FOCAR","FOGOS","FOLGA","FORCA","FORTE","FOSSA","FREVO",

"GABAR","GAIOL","GALHO","GANHO","GARFO","GELIA","GEMAS",
"GENIO","GERAL","GESSO","GIRAR","GOLPE","GORDA","GRAVE",
"GRITO","GRUPO","GUETO",

"HABIL","HASTE","HAVER","HERDA","HEROI","HIDRO","HONRA",
"HORDA","HOTEL",

"ICARO","IDEIA","IGUAL","IMOLA","IMPAR","INDIO","INVER",
"IRADO",

"JARRO","JUNTA","JURIS",

"LACRE","LAGOA","LANCE","LAPSO","LARAN","LASER",
"LEBRE","LEGAL","LEITO","LENHO","LESTE","LIMBO",
"LIMPA","LIVRO","LOBOU","LOMBO","LOUCO","LUCRO",

"MACRO","MADRE","MAGIA","MAGRO","MAIOR","MANGA",
"MANHA","MARCA","MARCO","MELRO","MENOR","MENTA",
"MENTE","MESMO","METAL","MICRO","MINAS","MISTO",
"MODAL","MOEDA","MORAL","MORFO","MOTEL",

"NABOS","NADAR","NARIZ","NAVIO","NEGRO","NINHO",
"NIVEL","NOBRE","NOITE","NORTE",

"OCUPA","OLIVA","OLHAR","ONDAS","OPACO","ORDEM",
"ORVAL","OUVIR",

"PADRA","PADRE","PAGAR","PALMA","PANEL","PAPEL",
"PARAR","PARES","PARTE","PASSA","PEDIR","PEIXE",
"PERDA","PERTO","PIANO","PILHA","PINTO","PLENO",
"PODER","POMBO","PONTE","PORTA",

"QUAIS","QUASE","QUEDA","QUILO",

"RAIVA","RAPTO","RASTO","REGRA","REINO","RESTA",
"RETAS","RISCO","RITMO","ROCHA","RODAR","ROUPA",

"SABER","SAIDA","SALTO","SANTO","SAUDE","SECAO",
"SENHA","SERIA","SERIO","SERRA","SIGMA","SOBRA",
"SOLTO","SONHO","SORVO","SORTE","SURDO",

"TACAO","TALHO","TARDE","TECLA","TEMPO","TENDA",
"TERMO","TIGRE","TINTA","TIRAR","TOTAL","TRAMA",
"TRIGO","TROCA",

"UNICO","USADO","UTERO",

"VALOR","VAPOR","VARAO","VELHO","VENTO","VERBO",
"VERDE","VICIO","VIDEO","VIGOR","VINHO","VISTA",

"ABRACO","ACIDO","ACUAR","ADOTE","AEREO","AFAGO","AGAVE",
"ALCAR","ALFAS","ALVOS","AMBAR","ANUAL","APOLO","ARADO",
"ARCAI","ARENA","ARGILA","AROMA","ASILO","ATLAS",

"BABEL","BACON","BAFIO","BALDE","BANAL","BARCA","BATEL",
"BEATA","BEDEL","BERRO","BICHO","BISPO","BLUSA","BOINA",
"BONUS","BORRA","BRASA","BRUMA",

"CACTO","CALHA","CALIX","CAMPO","CANAL","CAPUZ","CARDO",
"CARMA","CASAL","CASTO","CAUDA","CEIFA","CERVO","CHAGA",
"CHUVA","CIFRA","CIVIL","CLERO","CLIMA","CLIVO","COESA",
"COITO","COLMO","COMUM","COPIA","CORDA","COSMO","COTAR",
"CRASE","CRIVO","CROMO",

"DADOS","DAGMA","DANOS","DECAF","DECOR","DEIXA","DEMOS",
"DENSA","DEPOR","DERAM","DESCE","DIADE","DIZEM","DORSO",
"DUBIO",

"EBANO","ECLIP","EDIPO","EGIDE","EIXOS","ELIXI","EMULO",
"ENODO","ENSIO","ENTRA","ERGUI","ESFER","EXATO",

"FACES","FADAR","FALHA","FARSA","FAUNO","FEBRE","FENIX",
"FERAZ","FETAL","FIBRA","FIELA","FISCO","FLAMA","FLUIR",
"FOICE","FOSSO","FRASE","FRUTO","FUGAZ",

"GARRA","GASTO","GAZUA","GEADA","GEIRO","GEMER",
"GERME","GIRIA","GLOSA","GOMOS","GRAMA","GRIFO",
"GRUTA",

"HARPA","HASTE","HENRI","HERDE","HIDRA","HIFEN",
"HIPER","HUMUS",

"ICONE","IDOLA","IMAGO","INATO","INDUZ","INFER",
"INOVA",

"JAULA","JAZER","JUNCO","JURAR",

"LAPSO","LARVA","LAUDO","LEIGO","LEITE","LENTO",
"LESMA","LETAL","LIRIO","LITRO","LOGRO","LUCRO",
"LUMEN",

"MACRO","MAGMA","MAMBA","MANIA","MARCA","MELRO",
"MERCE","METRO","MIOLO","MOLAR","MORRO","MUSGO",

"NABAB","NARCO","NASAL","NEPAL","NEXOS","NIMBO",
"NINFA","NODAL","NORMA","NUTRI",

"OBICE","OBTER","OCULO","OFITO","OGIVA","OPALA",
"ORBIT","ORGIA","OSTRA",

"PACTO","PAGAO","PALCO","PANOS","PARCO","PARVO",
"PASTO","PAVIO","PEDAL","PELAS","PENAL","PERLA",
"PESAR","PISTA","PITON","PLAGA","PLENO","POLPA",
"PORTE","PRADO","PRUMO",

"QUARK","QUIBE","QUOTA",

"RAIAR","RAPAZ","RAZIA","RECIO","REDIL","RELES",
"RENAL","REVES","RIGOR","RINHA","ROTOR","RUBOR",

"SABIO","SAGAZ","SAETA","SALMO","SARAU","SEARA",
"SEIVA","SELIM","SENSO","SERVO","SIGLA","SISAL",
"SODIO","SOLDO","SONDA","SUINO","SULCO",

"TABOR","TALAR","TARSO","TATIL","TELHA","TENAZ",
"TENIS","TERNO","TILIA","TIMBO","TITAN","TOADA",
"TOLDO","TONAL","TORAX","TORPE","TRIBO",

"ULTRA","URANO","URDIR","VACUO","VADIO","VALIA",
"VENAL","VERAZ","VERGA","VERSO","VESGO","VINCO",
"VIRIL","VISCO","VITRO","VULGO",

"ZELAR","ZUNIR","CERTA","CERTO","FURIA", "CENSO","GAMES", "STEAM"



]



palavras_chutaveis = list(set(PALAVRAS))


