PALAVRAS = [
"ABACO","ABRIR","ACIDO","ACUME","ADUBA",
"AFAGO","AGUAS","ALADO","AMBAR",
"ANEXO","ANIMO","APICE","ARIDO","ARQUE",

"BALSA","BANDO","BARDO","BISPO","BRUMA",
"BURIL","CACAU","CALIX","CAMPO","CANIL",
"CARMA","CAVAL","CEDRO","CELTA","CERNE",

"CHAGA","CISMA","CLAVA","COESA","CORVO",
"CRIVO","CRUZA","CULTO","DAGMA","DADOS",

"DECOR","DEDOZ","DENSO","DESDE","TOTAL",
"DRAMA","EBANO","ECOAR","EDIPO",

"EXODO","ENTAO","ERETA",
"FARDO","FENIX","FERAZ","FIBRA",

"FUGAZ","GARRA","GENIO","GERME",
"GRUTA","HEROI","HIFEN","HUMUS","ICONE",

"IDEAL","IMPAR","INATO","INDIO","JAULA"
,"LAPSO","LARVA","LESTE","LIRIO",

"LIVRO","MACRO","MAGMA","MANIA","MELRO",
"MENTE","MISTO","MORFO","NOBRE","NOCHE",

"OCASO","ODIOS","ORVAL","OSSEO","PANDA",
"PENAL","PERIL","PLUMA","PRADO","QUIOS",

"RASTO","RELES","RISCO","ROTOR","SAGAZ",
"SALMO","SENIL","SERVO","SONDA","TACAO", 

"ZEBRA", "CERTA","CERTO","FURIA", "CENSO"

"GAMES", "STEAM","FURIA", "CENSO"
]


palavras_possiveis = list(set(PALAVRAS))




